/* helpers.js — 测试共用的构造函数。
 *
 * mkPuzzle 默认返回一道【完全合规】的题，各测试再按需破坏其中一处，
 * 于是每条断言都精确对应一个失败类别。
 */
(function (g) {
  'use strict';

  /** 构造一道合规的题。diff 默认 {1,1,1} → easy（于是不触发 hard 的额外要求）。 */
  function mkPuzzle(id, diff, opts) {
    opts = opts || {};
    /* ★ 必须深拷贝 difficulty，不能存调用方传进来的那个对象。
     *
     *   第一版写的是 `var d = diff || {...}` 然后 `difficulty: d` ——
     *   于是每个用同一个 EASY 常量建出来的题都【共享同一个对象】。
     *   测试里为了造坏用例而写 `delete p.difficulty.subject`，
     *   就把那个共享常量永久改坏了，之后所有题都跟着坏，
     *   而报错会出现在毫不相干的用例上（我第一次跑就踩了：5 个失败全来自这一处）。
     *
     *   题目对象在测试里是会被逐点破坏的，所以构造器必须交出彼此的独立副本。 */
    var d = diff
      ? JSON.parse(JSON.stringify(diff))
      : { tells: 1, subject: 1, postprocessing: 1 };
    return {
      id: id,
      status: 'ready',
      difficulty: d,
      images: [
        { id: id + '-1', src: 'assets/img/p/' + id + '/1.webp', isAI: false,
          width: 1200, height: 800, altKey: 'alt.imageSlot',
          provenance: { kind: 'microscopy', generator: null, prompt: null,
            credit: 'Prof. X, UGent', licence: 'Written permission', licenceUrl: null,
            sourceUrl: null, rightsCleared: true,
            permits: { web: true, publicDisplay: true, derivatives: true },
            ethicsCleared: true, rightsNote: 'ok' } },
        { id: id + '-2', src: 'assets/img/p/' + id + '/2.webp', isAI: true,
          width: 1200, height: 800, altKey: 'alt.imageSlot',
          provenance: { kind: 'ai', generator: 'Midjourney', model: 'v6.1',
            prompt: 'a fluorescent cell cluster', credit: null,
            licence: 'Generated by the author',
            permits: { web: true, publicDisplay: true, derivatives: true } } }
      ],
      teaching: {
        cue: 'cell-structure',
        tellRegion: { x: 0.6, y: 0.4, w: 0.18, h: 0.22 },
        explanation: { nl: 'uitleg', en: 'explanation' },
        kidLine: { nl: 'kijk', en: 'look' },
        rule: { nl: 'tel', en: 'count' },
        realNote: { nl: 'echt', en: 'real' }
      },
      meta: { author: 'a', reviewer: 'b', reviewedAt: '2026-09-22',
        verifiedSolution: opts.verifiedSolution === true, tags: [], notes: '' }
    };
  }

  /** 一组合规的题，档位可控。 */
  function mkSet(prefix, n, diff) {
    var out = [];
    for (var i = 0; i < n; i++) {
      out.push(mkPuzzle(prefix + String(i).padStart(2, '0'), diff));
    }
    return out;
  }

  g.AON_HELPERS = { mkPuzzle: mkPuzzle, mkSet: mkSet };
})(typeof window !== 'undefined' ? window : globalThis);
